import { type Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types ./types`.

export enum Status {
    ONLINE = "online",
    OFFLINE = "offline",
    AWAY = "away"
}

export enum CredibilityTier {
    BRONZE = "bronze",
    SILVER = "silver",
    GOLD = "gold",
    PLATINUM = "platinum",
    DIAMOND = "diamond"
}

export enum Type {
    GROUP = "group",
    CHANNEL = "channel",
    BOT = "bot",
    EXTENSION = "extension",
    PRIVATE = "private"
}

export enum Role {
    ADMIN = "admin",
    MEMBER = "member",
    OWNER = "owner",
    BOT = "bot",
    EXTENSION = "extension"
}

export enum Type {
    TEXT = "text",
    IMAGE = "image",
    FILE = "file",
    AUDIO = "audio",
    VIDEO = "video",
    STICKER = "sticker",
    SYSTEM = "system"
}

export enum Status {
    ACTIVE = "active",
    COOLDOWN = "cooldown",
    AVAILABLE = "available",
    BANNED = "banned"
}

export type Users = Models.Document & {
    userId: string;
    username: string;
    displayName: string | null;
    avatarUrl: string | null;
    bio: string | null;
    phone: string | null;
    email: string | null;
    publicKey: string;
    createdAt: string;
    lastSeen: string | null;
    status: Status | null;
    usernameCredibility: number | null;
    usernameHistory: string[] | null;
    usernameChangedAt: string | null;
    credibilityTier: CredibilityTier | null;
    credibilityScore: number | null;
    credibilityHistory: string[] | null;
    twoFactorEnabled: boolean | null;
    emailVerified: boolean | null;
    phoneVerified: boolean | null;
    encryptionKeyExported: boolean | null;
    recoveryPhraseBackedUp: boolean | null;
    encryptedPrivateKey: string | null;
    deleted: boolean | null;
}

export type Chats = Models.Document & {
    chatId: string;
    type: Type;
    title: string | null;
    avatarUrl: string | null;
    createdBy: Users;
    createdAt: string;
    updatedAt: string;
    isEncrypted: boolean | null;
    extensionType: string | null;
    deleted: boolean | null;
}

export type ChatMembers = Models.Document & {
    chatId: Chats;
    userId: Users;
    role: Role;
    joinedAt: string;
    mutedUntil: string | null;
    deleted: boolean | null;
}

export type Messages = Models.Document & {
    messageId: string;
    chatId: Chats;
    senderId: Users;
    content: string;
    type: Type | null;
    createdAt: string;
    editedAt: string | null;
    replyTo: Messages;
    isDeleted: boolean | null;
    extensionPayload: string | null;
    deleted: boolean | null;
}

export type Contacts = Models.Document & {
    ownerId: Users;
    createdAt: string;
    alias: string | null;
    deleted: boolean | null;
}

export type Devices = Models.Document & {
    deviceId: string;
    userId: Users;
    deviceType: string;
    pushToken: string | null;
    lastActive: string;
    deleted: boolean | null;
}

export type Bots = Models.Document & {
}

export type Web3wallets = Models.Document & {
}

export type Integrations = Models.Document & {
}

export type ExtensionSettings = Models.Document & {
}

export type Usernames = Models.Document & {
    username: string;
    status: Status;
    lastUsedBy: Users;
    lastUsedAt: string | null;
    cooldownUntil: string | null;
    history: string[] | null;
}
